# Generated by Django 5.2.7 on 2025-10-27 22:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='List ingredients, one per line')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('cuisine_type', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('french', 'French'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('african', 'African'), ('other', 'Other')], default='other', max_length=50)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('beverage', 'Beverage')], default='dinner', max_length=50)),
                ('dietary_tags', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('low_carb', 'Low Carb'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('none', 'None')], default='none', max_length=50)),
                ('prep_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cook_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='recipe_reci_created_48153f_idx'), models.Index(fields=['cuisine_type'], name='recipe_reci_cuisine_1ff39b_idx'), models.Index(fields=['meal_type'], name='recipe_reci_meal_ty_996cf6_idx'), models.Index(fields=['author'], name='recipe_reci_author__1bea12_idx')],
            },
        ),
    ]
