# Generated by Django 5.2.7 on 2025-11-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_rating_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved_by',
        ),
    ]
